Support more RSA and ECC key specs
JackOfMostTrades/aws-kms-pkcs11 pull request #27
Opened 2023-11-10 23:32 UTC by eager-signal

We needed support for 4096-bit RSA keys, but this adds support for all current RSA and ECC key specs.

2023-11-10 23:52 UTC, JackOfMostTrades commented on aws_kms_pkcs11.cpp
> +        return CKR_MECHANISM_INVALID;
Would work fine as it is, but as a matter of personal preference could you return this error as a default case in the above switch instead? (Then you can drop the if(keySize > 0) check and just break). Same with ECDSA below.

2023-11-11 00:33 UTC, JackOfMostTrades requested changes

2023-11-11 00:33 UTC, JackOfMostTrades commented on aws_kms_pkcs11.cpp
> +        }
Still need a break here I believe.
```suggestion
        }
        break;
```

2023-11-11 00:33 UTC, JackOfMostTrades commented on aws_kms_pkcs11.cpp
> +        }
```suggestion
        }
        break;
```

2023-11-11 00:51 UTC, eager-signal commented on aws_kms_pkcs11.cpp
> +        }
Ah, yep 🤦 . Thanks!

2023-11-11 01:38 UTC, JackOfMostTrades approved these changes

2023-11-11 01:38 UTC, JackOfMostTrades commented
Awesome, thanks!

2023-11-11 01:38 UTC, merged